---
name: Python lints

on:
  pull_request:
  push:

jobs:
  ruff:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
      - run: ruff check
      - run: ruff format --check
