# This workflow will build and (if release) publish Python distributions to PyPI
# For more information see:
#   - https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

name: Build artifact for PyPI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: pipx install build
    - name: Build wheels and a source tarball
      run: pyproject-build
    - name: Store the distribution packages
      uses: actions/upload-artifact@v4
      with:
        path: dist

  publish:
    name: Publish distribution
    runs-on: ubuntu-latest
    needs:
    - build
    if: github.event_name == 'release' && github.event.action == 'published'

    environment:
      name: pypi
      url: https://pypi.org/p/engibench
    permissions:
      id-token: write # For trusted publishing

    steps:
    - name: Download dists
      uses: actions/download-artifact@v4
      with:
        name: artifact
        path: dist

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
